// Code generated by hertz generator.

package model

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryjoblistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createjobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryjobdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _indicatorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryindicatorlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _query0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletejobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _query1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _runtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytasklistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _query2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _task_resultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytaskresultlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _query3Mw() []app.HandlerFunc {
	// your code...
	return nil
}
