name: Build and Push Docker Image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Log in to Alibaba Cloud Container Registry
        run: echo ${{ secrets.ALICLOUD_PASSWORD }} | docker login --username ${{ secrets.ALICLOUD_USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com

      - name: Build and push Docker image
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/qcq-wxl/miner_api:${{ env.TAG_NAME }} .
          docker push registry.cn-hangzhou.aliyuncs.com/qcq-wxl/miner_api:${{ env.TAG_NAME }}