// Code generated by hertz generator.

package model

import (
	"context"
	"miner_api/biz/common/Status"
	"miner_api/biz/sal/rpc/miner_core_rpc"

	model "miner_api/biz/model"

	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/wxl-server/common/gptr"
	"github.com/wxl-server/idl_gen/kitex_gen/miner_core"
)

// CreateJob .
// @router /job/create [POST]
func CreateJob(ctx context.Context, c *app.RequestContext) {
	NewCreateJobHandler(ctx, c).Handle()
}

type CreateJobHandler struct {
	ctx      context.Context
	hertzCtx *app.RequestContext

	respData *model.CreateJobData
}

func NewCreateJobHandler(ctx context.Context, hertzCtx *app.RequestContext) *CreateJobHandler {
	return &CreateJobHandler{
		ctx:      ctx,
		hertzCtx: hertzCtx,
	}
}

func (h *CreateJobHandler) Handle() {
	ctx := h.ctx
	var req model.CreateJobReq
	err := h.hertzCtx.BindAndValidate(&req)
	if err != nil {
		h.ReturnResp(Status.RequestParamsInvalid, err)
		return
	}

	token := h.hertzCtx.GetHeader("token")
	resp, err := miner_core_rpc.CreateJob(ctx, h.HttpReq2RpcReq(&req, token))
	if err != nil {
		logger.CtxErrorf(ctx, "miner_core_rpc.CreateJob failed, err = %v", err)
		h.ReturnResp(Status.InternalError, err)
		return
	}

	h.respData = h.RpcResp2HttpResp(resp)
	h.ReturnResp(Status.Success, err)
}

func (h *CreateJobHandler) HttpReq2RpcReq(httpReq *model.CreateJobReq, token []byte) *miner_core.CreateJobReq {
	return &miner_core.CreateJobReq{
		Name:        gptr.Indirect(httpReq.Name),
		Description: httpReq.Description,
		Token:       string(token),
	}
}

func (h *CreateJobHandler) RpcResp2HttpResp(rpcResp *miner_core.CreateJobResp) *model.CreateJobData {
	return &model.CreateJobData{
		Id: gptr.Of(rpcResp.Id),
	}
}

func (h *CreateJobHandler) ReturnResp(status *Status.Status, err error) {
	if err != nil {
		logger.CtxErrorf(h.ctx, "CreateJob failed, err = %v", err)
	}
	resp := new(model.CreateJobResp)
	resp.Code = status.Code()
	resp.Message = status.Message()
	if status.Code() == Status.Success.Code() && err == nil {
		resp.Data = h.respData
	}
	h.hertzCtx.JSON(consts.StatusOK, &resp)
}
