// Code generated by hertz generator.

package model

import (
	"context"
	"miner_api/biz/common/Status"
	"miner_api/biz/sal/rpc/miner_core_rpc"

	"github.com/bytedance/gopkg/util/logger"
	"github.com/qcq1/common/gptr"
	"github.com/qcq1/common/gslice"
	"github.com/qcq1/idl_gen/kitex_gen/miner_core"

	model "miner_api/biz/model"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryJobList .
// @router /job/query/list [POST]
func QueryJobList(ctx context.Context, c *app.RequestContext) {
	NewQueryJobListHandler(ctx, c).Handle()
}

type QueryJobListHandler struct {
	ctx      context.Context
	hertzCtx *app.RequestContext

	respData *model.QueryJobListData
}

func NewQueryJobListHandler(ctx context.Context, hertzCtx *app.RequestContext) *QueryJobListHandler {
	return &QueryJobListHandler{
		ctx:      ctx,
		hertzCtx: hertzCtx,
	}
}

func (h *QueryJobListHandler) Handle() {
	ctx := h.ctx
	var req model.QueryJobListReq
	err := h.hertzCtx.BindAndValidate(&req)
	if err != nil {
		h.hertzCtx.String(consts.StatusBadRequest, err.Error())
		return
	}

	coreResp, err := miner_core_rpc.QueryJobList(ctx, h.HttpReq2RpcReq(&req))
	if err != nil {
		logger.CtxErrorf(ctx, "miner_core.RawCall.QueryJobList failed, err = %v", err)
		return
	}

	h.respData = h.RpcResp2HttpResp(coreResp)
	h.ReturnResp(Status.Success, err)
}

func (h *QueryJobListHandler) ReturnResp(status *Status.Status, err error) {
	if err != nil {
		logger.CtxErrorf(h.ctx, "QueryJobList failed, err = %v", err)
	}
	resp := new(model.QueryJobListResp)
	resp.Code = status.Code()
	resp.Message = status.Message()
	if status.Code() == Status.Success.Code() && err == nil {
		resp.Data = h.respData
	}
	h.hertzCtx.JSON(consts.StatusOK, &resp)
}

func (h *QueryJobListHandler) HttpReq2RpcReq(httpReq *model.QueryJobListReq) *miner_core.QueryJobListReq {
	return &miner_core.QueryJobListReq{
		PageNum:  gptr.Indirect(httpReq.PageNum),
		PageSize: gptr.Indirect(httpReq.PageSize),
		OrderBy:  (*miner_core.JobColumn)(gptr.Of(int64(gptr.Indirect(httpReq.OrderBy)))),
		Order:    (*miner_core.Order)(gptr.Of(int64(gptr.Indirect(httpReq.Order)))),

		Id:             httpReq.Id,
		CreatedBy:      httpReq.CreatedBy,
		CreatedAtStart: httpReq.CreatedAtStart,
		CreatedAtEnd:   httpReq.CreatedAtEnd,
	}
}

func (h *QueryJobListHandler) RpcResp2HttpResp(rpcResp *miner_core.QueryJobListResp) *model.QueryJobListData {
	return &model.QueryJobListData{
		JobList: gslice.Map(rpcResp.JobList, func(v *miner_core.Job) *model.Job {
			return &model.Job{
				Id:          gptr.Of(v.Id),
				Name:        gptr.Of(v.Name),
				Description: gptr.Of(v.Description),
				CreatedBy:   gptr.Of(v.CreatedBy),
				UpdatedBy:   gptr.Of(v.UpdatedBy),
				CreatedAt:   gptr.Of(v.CreatedAt),
				UpdatedAt:   gptr.Of(v.UpdatedAt),
				Extra:       v.Extra,
			}
		}),
		Total: gptr.Of(rpcResp.Total),
	}
}
