// Code generated by hertz generator.

package model

import (
	"context"
	"miner_api/biz/common/Status"
	"miner_api/biz/sal/rpc/miner_core_rpc"

	model "miner_api/biz/model"

	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/wxl-server/common/gptr"
	"github.com/wxl-server/common/gslice"
	"github.com/wxl-server/idl_gen/kitex_gen/miner_core"
)

// QueryUserList .
// @router /user/query/list [POST]
func QueryUserList(ctx context.Context, c *app.RequestContext) {
	NewQueryUserListHandler(ctx, c).Handle()
}

type QueryUserListHandler struct {
	ctx      context.Context
	hertzCtx *app.RequestContext

	respData *model.QueryUserListData
}

func NewQueryUserListHandler(ctx context.Context, hertzCtx *app.RequestContext) *QueryUserListHandler {
	return &QueryUserListHandler{
		ctx:      ctx,
		hertzCtx: hertzCtx,
	}
}

func (h *QueryUserListHandler) Handle() {
	ctx := h.ctx
	var req model.QueryUserListReq
	err := h.hertzCtx.BindAndValidate(&req)
	if err != nil {
		h.ReturnResp(Status.RequestParamsInvalid, err)
		return
	}

	coreResp, err := miner_core_rpc.QueryUserList(ctx, h.HttpReq2RpcReq(&req))
	if err != nil {
		logger.CtxErrorf(ctx, "miner_core.RawCall.QueryUserList failed, err = %v", err)
		h.ReturnResp(Status.InternalError, err)
		return
	}

	h.respData = h.RpcResp2HttpResp(coreResp)
	h.ReturnResp(Status.Success, err)
}

func (h *QueryUserListHandler) ReturnResp(status *Status.Status, err error) {
	if err != nil {
		logger.CtxErrorf(h.ctx, "QueryUserList failed, err = %v", err)
	}
	resp := new(model.QueryUserListResp)
	resp.Code = status.Code()
	resp.Message = status.Message()
	if status.Code() == Status.Success.Code() && err == nil {
		resp.Data = h.respData
	}
	h.hertzCtx.JSON(consts.StatusOK, &resp)
}

func (h *QueryUserListHandler) HttpReq2RpcReq(httpReq *model.QueryUserListReq) *miner_core.QueryUserListReq {
	return &miner_core.QueryUserListReq{}
}

func (h *QueryUserListHandler) RpcResp2HttpResp(rpcResp *miner_core.QueryUserListResp) *model.QueryUserListData {
	return &model.QueryUserListData{
		UserList: gslice.Map(rpcResp.UserList, func(v *miner_core.User) *model.User {
			return &model.User{
				Id:    gptr.Of(v.Id),
				Email: gptr.Of(v.Email),
			}
		}),
	}
}
